//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBackup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleBackup.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; does not exist.{1}|Directory does not exist..
        /// </summary>
        internal static string msdDirNotExists {
            get {
                return ResourceManager.GetString("msdDirNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About - {0}|About as in about.
        /// </summary>
        internal static string msgAboutTitle {
            get {
                return ResourceManager.GetString("msgAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup must have a name.{0}|As said.
        /// </summary>
        internal static string msgBackupMustHaveName {
            get {
                return ResourceManager.GetString("msgBackupMustHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string msgConfirm {
            get {
                return ResourceManager.GetString("msgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete backup &apos;{0}&apos;?|Query to confirm a backup deletion.
        /// </summary>
        internal static string msgDeleteBackup {
            get {
                return ResourceManager.GetString("msgDeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories succeeded: {0}{1}|How many directories succeeded during backup operation.
        /// </summary>
        internal static string msgDirectoriesSucceeded {
            get {
                return ResourceManager.GetString("msgDirectoriesSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup directory hasn&apos;t changed.|As in the hash of the directory is the same..
        /// </summary>
        internal static string msgDirNotChanged {
            get {
                return ResourceManager.GetString("msgDirNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit backup|Edit backup.
        /// </summary>
        internal static string msgEditBackup {
            get {
                return ResourceManager.GetString("msgEditBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in script: &apos;{0}&apos;!|The SQL script has an error in it.
        /// </summary>
        internal static string msgErrorInScript {
            get {
                return ResourceManager.GetString("msgErrorInScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File fail ratio: {0} %|How many files in percentage failed compared to the total file amount in a backup operation.
        /// </summary>
        internal static string msgFileFailRatio {
            get {
                return ResourceManager.GetString("msgFileFailRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file name (&apos;{0}&apos;) contains invalid characters.{1}|File name contains invalid characters.
        /// </summary>
        internal static string msgFileNameInvalidChars {
            get {
                return ResourceManager.GetString("msgFileNameInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files failed: {0}{1}|How many files failed during backup operation.
        /// </summary>
        internal static string msgFilesFailed {
            get {
                return ResourceManager.GetString("msgFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files succeeded: {0}{1}|How many files succeeded during backup operation.
        /// </summary>
        internal static string msgFilesSucceeded {
            get {
                return ResourceManager.GetString("msgFilesSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID DATE/TIME|As it is.
        /// </summary>
        internal static string msgInvalidDatetime {
            get {
                return ResourceManager.GetString("msgInvalidDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some time occurences would be larger than a year.|Some time occurences in generated time values are too large.
        /// </summary>
        internal static string msgOccurencesLarge {
            get {
                return ResourceManager.GetString("msgOccurencesLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some time occurences would be smaller than five minutes.|Some time occurences in generated time values are too small.
        /// </summary>
        internal static string msgOccurencesSmall {
            get {
                return ResourceManager.GetString("msgOccurencesSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}|As in version.
        /// </summary>
        internal static string msgVersionText {
            get {
                return ResourceManager.GetString("msgVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running on the background...|As in running on the system tray...
        /// </summary>
        internal static string msgWorkBackground {
            get {
                return ResourceManager.GetString("msgWorkBackground", resourceCulture);
            }
        }
    }
}
